export interface ProvinceOption {
  province: string;
  wards: string[];
}

// 34 provinces/cities of Vietnam
export const locations: ProvinceOption[] = [
  { province: 'Hà Nội', wards: ['Ba Đình', 'Hoàn Kiếm', 'Đống Đa', 'Cầu Giấy', 'Thanh Xuân', 'Hà Đông'] },
  { province: 'TP. Hồ Chí Minh', wards: ['Quận 1', 'Quận 3', 'Quận 7', 'Thủ Đức', 'Bình Thạnh', 'Gò Vấp'] },
  { province: 'Hải Phòng', wards: ['Ngô Quyền', 'Lê Chân', 'Hồng Bàng', 'Kiến An'] },
  { province: 'Đà Nẵng', wards: ['Hải Châu', 'Thanh Khê', 'Sơn Trà', 'Ngũ Hành Sơn', 'Liên Chiểu'] },
  { province: 'Cần Thơ', wards: ['Ninh Kiều', 'Cái Răng', 'Bình Thủy'] },
  { province: 'An Giang', wards: ['Long Xuyên', 'Châu Đốc', 'Tịnh Biên'] },
  { province: 'Bà Rịa–Vũng Tàu', wards: ['Vũng Tàu', 'Bà Rịa', 'Phú Mỹ'] },
  { province: 'Bắc Giang', wards: ['Bắc Giang', 'Hiệp Hòa', 'Yên Dũng'] },
  { province: 'Bắc Ninh', wards: ['Bắc Ninh', 'Từ Sơn', 'Thuận Thành'] },
  { province: 'Bến Tre', wards: ['Thành phố Bến Tre', 'Châu Thành', 'Giồng Trôm'] },
  { province: 'Bình Dương', wards: ['Thủ Dầu Một', 'Dĩ An', 'Thuận An'] },
  { province: 'Bình Phước', wards: ['Đồng Xoài', 'Phước Long', 'Đồng Phú'] },
  { province: 'Bình Thuận', wards: ['Phan Thiết', 'Bắc Bình', 'Hàm Thuận Bắc'] },
  { province: 'Bình Định', wards: ['Quy Nhơn', 'An Nhơn', 'Tuy Phước'] },
  { province: 'Cà Mau', wards: ['Cà Mau', 'Đầm Dơi', 'Năm Căn'] },
  { province: 'Đắk Lắk', wards: ['Buôn Ma Thuột', "Ea H'leo", 'Buôn Hồ'] },
  { province: 'Đắk Nông', wards: ['Gia Nghĩa', 'Cư Jút', 'Đắk Mil'] },
  { province: 'Điện Biên', wards: ['Điện Biên Phủ', 'Mường Lay', 'Mường Nhé'] },
  { province: 'Đồng Nai', wards: ['Biên Hòa', 'Long Khánh', 'Trảng Bom'] },
  { province: 'Đồng Tháp', wards: ['Cao Lãnh', 'Sa Đéc', 'Hồng Ngự'] },
  { province: 'Gia Lai', wards: ['Pleiku', 'An Khê', 'Ayun Pa'] },
  { province: 'Hà Giang', wards: ['Hà Giang', 'Quản Bạ', 'Yên Minh'] },
  { province: 'Hà Nam', wards: ['Phủ Lý', 'Bình Lục', 'Duy Tiên'] },
  { province: 'Hà Tĩnh', wards: ['Hà Tĩnh', 'Hồng Lĩnh', 'Kỳ Anh'] },
  { province: 'Hậu Giang', wards: ['Vị Thanh', 'Ngã Bảy', 'Châu Thành'] },
  { province: 'Hưng Yên', wards: ['Hưng Yên', 'Văn Lâm', 'Yên Mỹ'] },
  { province: 'Khánh Hòa', wards: ['Nha Trang', 'Cam Ranh', 'Ninh Hòa'] },
  { province: 'Kiên Giang', wards: ['Rạch Giá', 'Phú Quốc', 'Hà Tiên'] },
  { province: 'Kon Tum', wards: ['Kon Tum', 'Đắk Tô', 'Ngọc Hồi'] },
  { province: 'Lâm Đồng', wards: ['Đà Lạt', 'Bảo Lộc', 'Đạ Huoai'] },
  { province: 'Lạng Sơn', wards: ['Lạng Sơn', 'Cao Lộc', 'Bắc Sơn'] },
  { province: 'Lào Cai', wards: ['Lào Cai', 'Sa Pa', 'Bảo Thắng'] },
  { province: 'Long An', wards: ['Tân An', 'Kiến Tường', 'Cần Giuộc'] },
  { province: 'Nam Định', wards: ['Nam Định', 'Vụ Bản', 'Giao Thủy'] },
  { province: 'Nghệ An', wards: ['Vinh', 'Nghi Lộc', 'Quỳnh Lưu'] },
  { province: 'Ninh Bình', wards: ['Ninh Bình', 'Tam Điệp', 'Nho Quan'] },
  { province: 'Phú Thọ', wards: ['Việt Trì', 'Phù Ninh', 'Tam Nông'] },
  { province: 'Phú Yên', wards: ['Tuy Hòa', 'Sông Cầu', 'Tuy An'] },
  { province: 'Quảng Bình', wards: ['Đồng Hới', 'Ba Đồn', 'Lệ Thủy'] },
  { province: 'Quảng Nam', wards: ['Tam Kỳ', 'Hội An', 'Quế Sơn'] },
  { province: 'Quảng Ngãi', wards: ['Quảng Ngãi', 'Sơn Tịnh', 'Tư Nghĩa'] },
  { province: 'Quảng Ninh', wards: ['Hạ Long', 'Móng Cái', 'Cẩm Phả'] },
  { province: 'Quảng Trị', wards: ['Đông Hà', 'Quảng Trị', 'Vĩnh Linh'] },
  { province: 'Sóc Trăng', wards: ['Sóc Trăng', 'Kế Sách', 'Mỹ Tú'] },
  { province: 'Sơn La', wards: ['Sơn La', 'Mộc Châu', 'Mai Sơn'] },
  { province: 'Tây Ninh', wards: ['Tây Ninh', 'Hòa Thành', 'Trảng Bàng'] },
  { province: 'Thái Bình', wards: ['Thái Bình', 'Hưng Hà', 'Quỳnh Phụ'] },
  { province: 'Thái Nguyên', wards: ['Thái Nguyên', 'Phổ Yên', 'Sông Công'] },
  { province: 'Thanh Hóa', wards: ['Thanh Hóa', 'Bỉm Sơn', 'Sầm Sơn'] },
  { province: 'Thừa Thiên-Huế', wards: ['Huế', 'Phong Điền', 'Quảng Điền'] },
  { province: 'Tiền Giang', wards: ['Mỹ Tho', 'Gò Công', 'Châu Thành'] },
  { province: 'Trà Vinh', wards: ['Trà Vinh', 'Càng Long', 'Cầu Ngang'] },
  { province: 'Tuyên Quang', wards: ['Tuyên Quang', 'Sơn Dương', 'Yên Sơn'] },
  { province: 'Vĩnh Long', wards: ['Vĩnh Long', 'Bình Minh', 'Long Hồ'] },
  { province: 'Vĩnh Phúc', wards: ['Vĩnh Yên', 'Phúc Yên', 'Sông Lô'] },
  { province: 'Yên Bái', wards: ['Yên Bái', 'Trấn Yên', 'Văn Yên'] },
  { province: 'Bạc Liêu', wards: ['Bạc Liêu', 'Hòa Bình', 'Vĩnh Lợi'] },
  { province: 'Bắc Kạn', wards: ['Bắc Kạn', 'Chợ Đồn', 'Na Rì'] },
  { province: 'Cao Bằng', wards: ['Cao Bằng', 'Hòa An', 'Nguyên Bình'] },
  { province: 'Hải Dương', wards: ['Hải Dương', 'Chí Linh', 'Nam Sách'] },
  { province: 'Hòa Bình', wards: ['Hòa Bình', 'Lương Sơn', 'Kim Bôi'] },
  { province: 'Lai Châu', wards: ['Lai Châu', 'Tam Đường', 'Sìn Hồ'] },
  { province: 'Tuyên Quang', wards: ['Tuyên Quang', 'Sơn Dương', 'Yên Sơn'] },
];